import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/navigation";
import Logo from "@/assets/images/logo.svg";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header className="flex items-center justify-between py-8 lg:py-12 px-4 md:px-8 max-w-screen-xl ml-auto mr-auto">
          <Image src={Logo} alt="logo" />
          <Navigation />
        </header>
        {children}
      </body>
    </html>
  );
}
